spring:
  application:
    name: 'customermanagement'
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer-database

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "healthcheck"